### ISSUE TITLE
I want to read and store Plex information in a database

### ISSUE THREAD

**Issue by OverloadUT** [OverloadUT/alexa-plex#10]

**Comment by BindersFullOfWomen** [comment]
what do you mean by "information," like meta data?

**Comment by OverloadUT** [comment]
Most everything that is currently set up as env variables: auth token, cached ip addresses and device uuids

**Comment by BindersFullOfWomen** [comment]
Ah OK, gotcha.

**Comment by OverloadUT** [comment]
Added in 65d4af9!
