### ISSUE TITLE
I want a PIN-based Plex authentication system

### ISSUE THREAD

**Issue by OverloadUT** [OverloadUT/alexa-plex#11]
Need to reverse engineer how the Plex Home Theater does it

**Comment by BindersFullOfWomen** [comment]
You could try looking at the code for the [Plex for Samsung ](https://blog.plex.tv/2012/08/03/welcoming-plex-on-samsung/). Not sure if it's open sourced or not though.

**Comment by OverloadUT** [comment]
Added in 65d4af9!
