### ISSUE TITLE
I want to configure the app with a "setup" process

### ISSUE THREAD

**Issue by OverloadUT** [OverloadUT/alexa-plex#12]
Should authenticate via PIN, and configure which player(s) to work with

**Comment by BindersFullOfWomen** [comment]
My recommendation would be to have Alexa read off a PIN, then the user would go to https://plex.tv/pin on their device to enter the pin. This way you aren't passing any login credentials through Alexa.

**Comment by OverloadUT** [comment]
Yep, that is #11!

**Comment by OverloadUT** [comment]
Added in 65d4af9! It's just for PIN auth and you can't configure your player/server yet but the framework is there.
