### ISSUE TITLE
I want to resume an episode where I left off

### ISSUE THREAD

**Issue by OverloadUT** [OverloadUT/alexa-plex#5]
Should Alexa always prompt when attempting to play an episode that is part way through?

**Comment by BindersFullOfWomen** [comment]
Yes. 

If possible, give the same options that Plex natively offers (Resume at __:__ or start from beginning)

**Comment by OverloadUT** [comment]
Yeah, the problem is that in a voice control environment anything that requires extra user input is a LOT more time consuming than in a visual interface. They should be kept to only when absolutely necessary.

I'm thinking that:

1. If you are playing a random episode, it should always start from the beginning. It would be weird to randomly select an episode that happened to be partially played anyway.
2. If you are playing the "next unwatched episode" it will always resume from where you left off. This is because the context here is "continuing your show", so starting from exactly where you were makes sense.
3. If you request a SPECIFIC episode, then you get the prompt if necessary.

Of course, you should always be able to override this by saying so in the original request "play the next episode of Game of Thrones and start from the beginning"

**Comment by BindersFullOfWomen** [comment]
I agree with all three.

**Comment by SwissKid** [comment]
You could also have a prompt - a yes/no prompt isn't that hard to do, and I know that I have very few items that are only partially watched.
"Watch the next episode of dilbert"
"Would you like to continue where you left off?"
"Yes"

**Comment by OverloadUT** [comment]
Yeah, that's the plan for scenario 3. It will require real-world testing and feedback to verify that my proposals for 1 and 2 are correct, so we'll see :)

**Comment by BindersFullOfWomen** [comment]
I'm happy to help beta test if/when you need testers
